### ISSUE TITLE
TCP Zero Window on high throughput - Async mode TRX Bind with Delivery

### ISSUE THREAD

**Issue by talalanwar** [OpenSmpp/opensmpp#32]
We are sending high throughput SUBMIT_SM using OpenSMPP. But TCP ZeroWindow is received most of the times. Deliver_SM and SUBMIT_SM_RESP is getting missed. Please suggest how to resolve this.

  TPS: 1000 msg/s for SUBMIT_SM   and similar is on PDUListerener(DeliverSM/SUBMIT_SM_RESP)

**Comment by talalanwar** [comment]
@ptomli @man8 @thiamteck @paoloc0 @vasyaod 
Please have a look at the issue guys.

**Comment by paoloc0** [comment]
You haven't provided much information. I presume the client is receiving the ZeroWindow responses from the server. I don't know if you are using OpenSMPP on the server side as well as the client side. Data can't go missing at the TCP level, so I presume that the PDUs are "getting missed" because a series of ZeroWindow events causes the TCP connection to eventually reset, and the server doesn't resend the PDUs after the rebind. But those are a lot of assumptions.

All that aside: even presuming that OpenSMPP is running on the server side, the ZeroWindow responses imply that the server you are speaking to is too busy (for various definitions of "busy") at the time to accept the data on the socket. This is a tuning issue, with many potential application-specific and OS-specific issues that could fall outside of the OpenSMPP library, and which is not likely to be answerable here.

**Comment by talalanwar** [comment]
@paoloc0 
Thanks for your response.

TCP ZeroWindow is seen as part of SUBMIT_SM Packets sent from client. We have verified this from captured tcpdump using wireshark. Below is an example.
![image](https://user-images.githubusercontent.com/932237/34779231-6058aa30-f641-11e7-8d04-50b7e3967c50.png)

I have searched the whole dump and not seen a single FIN packet. Also there is no rebind captured in the tcpdump trace and application logs.

Server is not using OpenSMPP its a commercial solution, OpenSMPP is only used on client side.

This behavior is noticed when amount of data increases. Our concern is whether OpenSMPP build supports high throughput of 1000 to 1500 PDUs/second on sender/receiver both using any TRX,TX,RX combinations.

**Comment by paoloc0** [comment]
I can't say what sort of throughput you could ideally achieve using OpenSMPP (I haven't personally had a need for anything near 1000/second), but the ZeroWindow responses do indicate that the server application is too busy to handle the data (it can't keep up with the network stack). I would have expected that the server starts returning throttled responses to you before something like this happens, but maybe it's not well-behaved, or maybe there's something you can configure. You should also ensure that your window size (not TCP window size, but rather the number of unacknowledged PDUs that your client allows to be in play at any point in time) is limited to what the server expects / can handle. You should look at the server's load average and swap rate at the time as well. Maybe you've exceeded the rate that the server was written to handle.

In principle the ZeroWindow responses should not cause any great harm, except to throttle your connection, and thus I wonder if your missing PDUs might have a different cause. But given that the connection might stall for thirty seconds or even longer, depending on your client OS (see e.g. wesmorgan.blogspot.com/2011/03/tcp-zero-windows-and-why-they-can-be.html ), that could be long enough to confuse things on either the server side or your own client software (that you wrote around OpenSMPP).

Anyway, I can't really offer more help than that. It sounds outside of the scope of the OpenSMPP client software project. Good luck.
