### ISSUE TITLE
How to make a long Connection

### ISSUE THREAD

**Issue by xbsbsvjshs** [OpenSmpp/opensmpp#49]
Does this open source project support long connections? How to transform without support? Anybody know? 
Thank you very much!

**Comment by paoloc0** [comment]
Hi. You will have to give a lot more detail - it's not clear what you are trying to achieve

**Comment by xbsbsvjshs** [comment]
I want to send multiple messages at the same time, but the current situation is that every time I send a message, I need to connect once, which wastes resources and time. I want to keep the connection open until the client or server doesn't request it.
Thank you!

**Comment by paoloc0** [comment]
You definitely don't need to connect every time. If you find that you are being automatically disconnected, perhaps it is because you are not sending `enquire_link`s, or replying to `enquire_link`s sent to you by the server.

Try running [the client](https://github.com/OpenSmpp/opensmpp/blob/master/client/src/main/java/org/smpp/test/SMPPTest.java) and testing with that - then you can use it as a basis for further development.

**Comment by xbsbsvjshs** [comment]
Does this case support long time connection and keep the connection open？

**Comment by paoloc0** [comment]
The client will keep the connection open indefinitely, yes. The connection will only be shut down if the server chooses to disconnect you (e.g. because you don't respond to `enquire_link`s).

**Comment by xbsbsvjshs** [comment]
ESME already in bound State when sending multiple messages at the same time. Do you know the reason？
Thank you!

**Comment by paoloc0** [comment]
I suggest that you try to use the client as a starting point. If you can achieve what you want with the client, then you can use the client code as an example to build upon.

**Comment by xbsbsvjshs** [comment]
bound =bind();
		if(bound) {
			Iterator<String> it = destinations.iterator();
			while(it.hasNext()) {
					String d = it.next();
					boolean iSuccess =submit(d, message, sender, senderTon, senderNpi);
			}
		unbind();


So every time I call this method here, I'm going to bind, so how do I get out of bind here, and just keep sending text messages using the previous connection。
Thank you very much!

**Comment by xbsbsvjshs** [comment]
public boolean sendSms(String serviceNum,String msg,String fromType){
     bound =bind();
	if(bound) {
		Iterator<String> it = destinations.iterator();
		while(it.hasNext()) {
				String d = it.next();
				boolean iSuccess =submit(d, message, sender, senderTon, senderNpi);
		}
	unbind();
}


Each time the sendSMS method is called, a bind is performed, and I think the next time the SMS method is called, instead of a bind, use the previous bind.
Thank you!

**Comment by paoloc0** [comment]
You can bind before you call `sendSms` - and don't call `unbind` at all.

I can't help more with the specifics, but I can suggest that, instead of using this library, which requires a lot of low-level programming, and knowledge of the SMPP specification, you instead consider using a pre-built solution like Kannel: https://www.kannel.org/
